### ISSUE TITLE
Home page too slow

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/bangalore.python.org.in#19]
Home page is loading all posts from archives which is making it too slow(~2 minutes).

It would be great if we show only recent post or recent 5 posts on home page.

**Comment by ChillarAnand** [comment]
Migrate to lektor or nikola?

**Comment by anandology** [comment]
One other related issue is that the images used are very big (in the order of 2MB and more) and it takes too long to load them. Using scaled versions of the images would be useful.

**Comment by ChillarAnand** [comment]
:+1:

**Comment by anandology** [comment]
Looks like all we need is to enable pagination in Jekyll.

https://jekyllrb.com/docs/pagination/

**Comment by ChillarAnand** [comment]
I guess this blog is built with mynt and it doesn't support pagination.

**Comment by anistark** [comment]
Moved to jekyll and added pagination with new design. Faster load now. Closing this.
